name: Build, Rename, and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 当推送符合 vX.X.X 格式的标签时触发

jobs:
  build:
    runs-on: windows-latest  # 指定 Windows 环境，适配 net6.0-windows7.0

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # 确保使用 .NET 6.0

      - name: 恢复依赖项
        run: dotnet restore

      - name: 构建项目
        run: dotnet build --configuration Release

      - name: 发布应用程序
        run: dotnet publish -c Release -o publish

      - name: 重命名文件
        run: |
          cd publish
          ren AshClicker.exe 岚尘按键.exe  # 使用 Windows 命令重命名文件

      - name: 打包压缩文件
        run: |
          cd publish
          powershell Compress-Archive -Path * -DestinationPath ../岚尘按键-v${{ github.ref_name }}.zip

      - name: 计算指纹
        run: |
          cd publish
          certutil -hashfile 岚尘按键.exe SHA256 >> ../指纹信息.txt
          certutil -hashfile ../岚尘按键-v${{ github.ref_name }}.zip SHA256 >> ../指纹信息.txt
          type ../指纹信息.txt

      - name: 创建 Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            以下是生成的文件指纹（SHA256）：
            ```
            ${{ steps.hash_output.outputs.hashes }}
            ```

            **验证文件完整性：**
            1. 在 Windows 系统中打开命令提示符。
            2. 输入以下命令以验证指纹：
               ```
               certutil -hashfile 文件路径 SHA256
               ```
            3. 比较输出的指纹值与此处列出的指纹是否一致。
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传压缩文件
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 岚尘按键-v${{ github.ref_name }}.zip
          asset_name: 岚尘按键-v${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: 上传指纹文件
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 指纹信息.txt
          asset_name: 指纹信息.txt
          asset_content_type: text/plain
